import { TradeType } from "@/types";

export interface TradeDefinition {
  id: TradeType;
  name: string;
  icon: string;
  description: string;
  services: string[];
  materials: string[];
  equipment: string[];
  measurements: string[];
  insuranceTerms: string[];
}

export const TRADE_DEFINITIONS: Record<TradeType, TradeDefinition> = {
  landscaping: {
    id: "landscaping",
    name: "Landscaping",
    icon: "🌿",
    description: "Lawn care, hardscaping, and outdoor design",
    services: [
      "Lawn Installation",
      "Sod Installation",
      "Landscape Design",
      "Hardscaping",
      "Irrigation Systems",
      "Tree Planting",
      "Mulching",
      "Lawn Maintenance",
      "Garden Beds",
      "Retaining Walls",
    ],
    materials: [
      "Sod (sq ft)",
      "Mulch (cu yd)",
      "Topsoil (cu yd)",
      "Pavers (sq ft)",
      "Gravel (ton)",
      "Plants",
      "Irrigation Pipe (ft)",
      "Landscape Fabric (roll)",
    ],
    equipment: [
      "Mower",
      "Edger",
      "Blower",
      "Trimmer",
      "Aerator",
      "Dethatcher",
      "Sod Cutter",
      "Plate Compactor",
    ],
    measurements: ["Lawn Area", "Hardscape Area", "Garden Beds", "Property Perimeter"],
    insuranceTerms: [
      "Work will be performed in accordance with industry standards",
      "Property damage coverage up to $1,000,000",
      "General liability insurance certificate provided upon request",
    ],
  },
  roofing: {
    id: "roofing",
    name: "Roofing",
    icon: "🏠",
    description: "Roof installation, repair, and inspection",
    services: [
      "Roof Replacement",
      "Roof Repair",
      "Roof Inspection",
      "Shingle Installation",
      "Metal Roof Installation",
      "Flat Roof Repair",
      "Gutter Installation",
      "Skylight Installation",
      "Emergency Repairs",
      "Insurance Claims",
    ],
    materials: [
      "Shingles (sq)",
      "Underlayment (roll)",
      "Drip Edge (ft)",
      "Ridge Cap (ft)",
      "Valley Metal (ft)",
      "Flashing (ft)",
      "Roof Nails (lb)",
      "Ice & Water Shield (roll)",
    ],
    equipment: [
      "Roof Jacks",
      "Safety Harness",
      "Nail Gun",
      "Compressor",
      "Ladder",
      "Scaffolding",
      "Dumpster",
      "Magnetic Sweeper",
    ],
    measurements: [
      "Total Roof Area",
      "Roof Pitch",
      "Number of Facets",
      "Ridge Length",
      "Valley Length",
      "Eves Length",
    ],
    insuranceTerms: [
      "All work backed by manufacturer's warranty",
      "Workmanship warranty: 10 years labor",
      "Material warranty as provided by manufacturer",
      "Licensed and insured roofing contractor",
      "Insurance claims assistance provided",
    ],
  },
  siding: {
    id: "siding",
    name: "Siding",
    icon: "🏢",
    description: "Siding installation and exterior cladding",
    services: [
      "Vinyl Siding",
      "Fiber Cement Siding",
      "Wood Siding",
      "Metal Siding",
      "Siding Repair",
      "Siding Replacement",
      "Exterior Trim",
      "Soffit & Fascia",
    ],
    materials: [
      "Siding Panels (sq)",
      "House Wrap (roll)",
      "J-Channel (ft)",
      "Trim Boards (ft)",
      "Soffit (sq ft)",
      "Fascia (ft)",
      "Siding Nails (lb)",
      "Caulk (tube)",
    ],
    equipment: [
      "Siding Brake",
      "Circular Saw",
      "Table Saw",
      "Nail Gun",
      "Scaffolding",
      "Ladders",
      "Safety Equipment",
    ],
    measurements: ["Total Wall Area", "Windows", "Doors", "Exterior Perimeter", "Stories"],
    insuranceTerms: [
      "Licensed siding contractor",
      "All materials include manufacturer warranty",
      "Labor warranty: 5 years",
      "Weather-tight installation guaranteed",
    ],
  },
  painting: {
    id: "painting",
    name: "Painting",
    icon: "🎨",
    description: "Interior and exterior painting services",
    services: [
      "Exterior Painting",
      "Interior Painting",
      "Cabinet Painting",
      "Deck Staining",
      "Drywall Repair",
      "Pressure Washing",
      "Color Consultation",
      "Commercial Painting",
    ],
    materials: [
      "Paint (gal)",
      "Primer (gal)",
      "Stain (gal)",
      "Caulk (tube)",
      "Sandpaper",
      "Painter's Tape (roll)",
      "Drop Cloths",
      "Wood Filler",
    ],
    equipment: [
      "Paint Sprayer",
      "Brushes",
      "Rollers",
      "Ladders",
      "Scaffolding",
      "Power Washer",
      "Sanders",
      "Paint Trays",
    ],
    measurements: ["Wall Area", "Ceiling Area", "Trim Length", "Door Count", "Window Count"],
    insuranceTerms: [
      "Professional painting contractor",
      "All work guaranteed for 2 years",
      "Premium paint products used",
      "Full property protection during work",
    ],
  },
  hvac: {
    id: "hvac",
    name: "HVAC",
    icon: "❄️",
    description: "Heating, ventilation, and air conditioning",
    services: [
      "AC Installation",
      "Furnace Installation",
      "Heat Pump Installation",
      "HVAC Repair",
      "Duct Cleaning",
      "Maintenance Plans",
      "Emergency Service",
      "Air Quality Testing",
      "Thermostat Installation",
    ],
    materials: [
      "AC Unit (ton)",
      "Furnace",
      "Ductwork (ft)",
      "Refrigerant (lb)",
      "Air Filters",
      "Thermostat",
      "Insulation (ft)",
      "Registers",
    ],
    equipment: [
      "Vacuum Pump",
      "Manifold Gauges",
      "Recovery Machine",
      "Leak Detector",
      "Multimeter",
      "Duct Tools",
      "Torch Kit",
    ],
    measurements: ["Square Footage", "Number of Zones", "Duct Runs", "Vents"],
    insuranceTerms: [
      "Licensed HVAC contractor",
      "Equipment warranty as provided by manufacturer",
      "Labor warranty: 1 year",
      "EPA certified technicians",
      "Permit and inspection included where required",
    ],
  },
  plumbing: {
    id: "plumbing",
    name: "Plumbing",
    icon: "🚰",
    description: "Plumbing installation, repair, and maintenance",
    services: [
      "Pipe Repair",
      "Drain Cleaning",
      "Water Heater Installation",
      "Fixture Installation",
      "Sewer Line Repair",
      "Leak Detection",
      "Repiping",
      "Emergency Plumbing",
      "Backflow Testing",
    ],
    materials: [
      "Copper Pipe (ft)",
      "PEX Pipe (ft)",
      "PVC Pipe (ft)",
      "Fittings",
      "Water Heater",
      "Fixtures",
      "Shut-off Valves",
      "Solder",
    ],
    equipment: [
      "Pipe Wrench",
      "Drain Snake",
      "Pipe Cutter",
      "Torch",
      "Camera Inspection",
      "Hydro Jetter",
      "Thread Machine",
    ],
    measurements: ["Pipe Runs", "Fixtures", "Drain Lines", "Water Lines"],
    insuranceTerms: [
      "Licensed master plumber",
      "All work to code",
      "Warranty: 1 year labor, manufacturer warranty on parts",
      "Permit obtained where required",
    ],
  },
  electrical: {
    id: "electrical",
    name: "Electrical",
    icon: "⚡",
    description: "Electrical installation and repair services",
    services: [
      "Panel Upgrades",
      "Wiring",
      "Outlet Installation",
      "Lighting Installation",
      "Generator Installation",
      "EV Charger Installation",
      "Ceiling Fan Installation",
      "Electrical Repairs",
      "Code Compliance",
    ],
    materials: [
      "Wire (ft)",
      "Circuit Breakers",
      "Outlets",
      "Switches",
      "Light Fixtures",
      "Conduit (ft)",
      "Junction Boxes",
      "Wire Nuts",
    ],
    equipment: [
      "Multimeter",
      "Wire Stripper",
      "Conduit Bender",
      "Fish Tape",
      "Drill",
      "Voltage Tester",
      "Crimpers",
    ],
    measurements: ["Wire Runs", "Circuits", "Outlets", "Fixtures", "Panels"],
    insuranceTerms: [
      "Licensed electrician",
      "All work to NEC standards",
      "Permit and inspection included",
      "Warranty: 1 year on labor",
    ],
  },
  tree_service: {
    id: "tree_service",
    name: "Tree Service",
    icon: "🌳",
    description: "Tree removal, trimming, and care",
    services: [
      "Tree Removal",
      "Tree Trimming",
      "Stump Grinding",
      "Tree Health Assessment",
      "Emergency Storm Damage",
      "Cabling & Bracing",
      "Land Clearing",
      "Firewood Delivery",
    ],
    materials: [
      "Wood Chips (cu yd)",
      "Cables",
      "Braces",
      "Tree Supports",
      "Fertilizer",
    ],
    equipment: [
      "Chainsaw",
      "Wood Chipper",
      "Stump Grinder",
      "Bucket Truck",
      "Crane",
      "Ropes & Rigging",
      "Safety Gear",
    ],
    measurements: ["Tree Height", "Tree Diameter", "Number of Trees", "Stump Size"],
    insuranceTerms: [
      "Certified arborist on staff",
      "Full liability and workers comp insurance",
      "Property damage coverage",
      "Debris removal included",
    ],
  },
  pool_service: {
    id: "pool_service",
    name: "Pool Service",
    icon: "🏊",
    description: "Pool maintenance, repair, and installation",
    services: [
      "Pool Cleaning",
      "Chemical Balancing",
      "Equipment Repair",
      "Pool Opening/Closing",
      "Pump Replacement",
      "Filter Maintenance",
      "Tile Cleaning",
      "Leak Detection",
      "Pool Renovation",
    ],
    materials: [
      "Chlorine (lb)",
      "pH Adjuster",
      "Algaecide (gal)",
      "Pool Salt (bag)",
      "Filter Media",
      "Pool Tiles (sq ft)",
      "Plaster (sq ft)",
    ],
    equipment: [
      "Pool Vacuum",
      "Test Kit",
      "Skimmer Net",
      "Brush",
      "Pump",
      "Filter",
      "Heater",
    ],
    measurements: ["Pool Volume", "Surface Area", "Depth", "Deck Area"],
    insuranceTerms: [
      "Licensed pool contractor",
      "All chemicals handled per safety standards",
      "Equipment warranty per manufacturer",
      "Service guarantee",
    ],
  },
  pressure_washing: {
    id: "pressure_washing",
    name: "Pressure Washing",
    icon: "💦",
    description: "Exterior cleaning and surface preparation",
    services: [
      "House Washing",
      "Driveway Cleaning",
      "Deck Cleaning",
      "Roof Cleaning",
      "Gutter Cleaning",
      "Concrete Cleaning",
      "Fence Cleaning",
      "Commercial Cleaning",
    ],
    materials: [
      "Cleaning Solution (gal)",
      "Detergent (gal)",
      "Bleach (gal)",
      "Sealer (gal)",
    ],
    equipment: [
      "Pressure Washer",
      "Surface Cleaner",
      "Extension Wands",
      "Hoses",
      "Water Tank",
      "Chemical Injector",
    ],
    measurements: ["Surface Area", "Linear Feet", "Story Height", "Deck Area"],
    insuranceTerms: [
      "Professional cleaning service",
      "Property damage insurance",
      "Satisfaction guaranteed",
      "Safe for all surfaces when properly applied",
    ],
  },
  renovation: {
    id: "renovation",
    name: "Renovation",
    icon: "🔨",
    description: "Home remodeling and renovation projects",
    services: [
      "Kitchen Remodel",
      "Bathroom Remodel",
      "Basement Finishing",
      "Room Additions",
      "Whole House Renovation",
      "Flooring",
      "Drywall",
      "Framing",
      "Demo Work",
    ],
    materials: [
      "Lumber (bd ft)",
      "Drywall (sheet)",
      "Flooring (sq ft)",
      "Cabinets",
      "Countertops (sq ft)",
      "Fixtures",
      "Tile (sq ft)",
      "Trim (ft)",
    ],
    equipment: [
      "Table Saw",
      "Miter Saw",
      "Nail Gun",
      "Drywall Tools",
      "Tile Saw",
      "Demolition Tools",
      "Scaffolding",
    ],
    measurements: ["Room Dimensions", "Wall Area", "Floor Area", "Ceiling Height"],
    insuranceTerms: [
      "Licensed general contractor",
      "All work to building code",
      "Permits obtained and managed",
      "Warranty: 1 year on workmanship",
      "Progress payment schedule",
    ],
  },
  general_contractor: {
    id: "general_contractor",
    name: "General Contractor",
    icon: "🏗️",
    description: "Full-service contracting and project management",
    services: [
      "Project Management",
      "New Construction",
      "Renovations",
      "Repairs",
      "Additions",
      "Site Work",
      "Subcontractor Management",
      "Permit Acquisition",
    ],
    materials: ["Varies by project"],
    equipment: ["Full contractor equipment fleet"],
    measurements: ["Property Assessment", "As Required by Project"],
    insuranceTerms: [
      "Licensed general contractor",
      "Full liability insurance",
      "Workers compensation coverage",
      "All permits and inspections managed",
      "Warranty terms per contract",
    ],
  },
};

export const getAllTradeTypes = (): TradeType[] => {
  return Object.keys(TRADE_DEFINITIONS) as TradeType[];
};

export const getTradeDefinition = (tradeType: TradeType): TradeDefinition => {
  return TRADE_DEFINITIONS[tradeType];
};

export const getTradeServices = (tradeType: TradeType): string[] => {
  return TRADE_DEFINITIONS[tradeType]?.services || [];
};

export const getTradeMaterials = (tradeType: TradeType): string[] => {
  return TRADE_DEFINITIONS[tradeType]?.materials || [];
};

export const getTradeEquipment = (tradeType: TradeType): string[] => {
  return TRADE_DEFINITIONS[tradeType]?.equipment || [];
};
